Repository BeFit-crew/BeFit, pull requests merged in 2025-06, with the labels that each got.

#15 [기능] Infermedica 페이지 API 모달 구조 및 기능 구현 [수정] index.html 정리
  index.html
  src/infermedica/infermedica.css
  src/infermedica/infermedica.html
  src/infermedica/infermedica.js
Labels: feature

#23 [기능] Gemini API 키, 연동,초기 역할 부여 프롬프트(SYSTEM_PROMPT) 작성, 정상 작동 확인 [버그수정] API 작동 불가 확인 및 대체 API 조사
  assets/css/main.css
  index.html
  src/infermedica/infermedica.js
Labels: bug, feature, ai

#32 [기능] 입력 항목 개선, AI 응답 포맷 변경, 회의록/가이드 문서 작성
  .gitignore
  README.md
  docs/How_To_Use_AI_Data.md
  docs/befit_team_rules.md
  docs/meetings/2025-06-23-meeting.md
  docs/meetings/2025-06-24-meeting.md
  docs/meetings/2025-06-25-meeting.md
  docs/meetings/2025-06-26-meeting.md
  src/befit-ai/befit-ai.css
  src/befit-ai/befit-ai.html
  src/befit-ai/befit-ai.js
  src/befit-ai/img/be-fit-logo-white.png
Labels: docs, feature, discussion, refactor, frontend, ai

#39 [기능/리팩토링/문서] 사용자 입력 개선, 반응형 UI 정리, 코드 모듈화 및 팀 규칙 문서화
  docs/How_To_Use_AI_Data.md
  docs/befit_team_rules.md
  docs/meetings/2025-06-25-meeting.md
  docs/meetings/2025-06-26-meeting.md
  docs/meetings/2025-06-27-meeting.md
  docs/team_rules/Coding_Convention.md
  docs/team_rules/GitHub_Collaboration.md
  docs/team_rules/Git_Workflow.md
  docs/team_rules/befit_team_rules.md
  src/befit-ai/befit-ai.css
  src/befit-ai/befit-ai.html
  src/befit-ai/befit-ai.js
  src/befit-ai/modules/api-befit-ai.js
  src/befit-ai/modules/constants-befit-ai.js
  src/befit-ai/modules/dom-befit-ai.js
  src/befit-ai/modules/storage-befit-ai.js
  src/befit-ai/modules/ui-befit-ai.js
  src/befit-ai/modules/utils-befit-ai.js
Labels: docs, feature, refactor, frontend

#43 feat : 공통헤더 및 색상 적용, fix : 모듈화된 파일 접근 코드 수정
  src/shopping/shopping.css
  src/shopping/shopping.html
  src/shopping/shopping.js
Labels: bug, feature, design
