Repository BeFit-crew/BeFit, pull requests merged in 2025-07, with the labels that each got.

#47 API 연동 기반 추천 시스템 구현 및 UI 공통 스타일 적용
  src/playlist/playlist.css
  src/playlist/playlist.html
  src/playlist/playlist.js
Labels: bug, design

#48 [feat] 쇼핑 리스트 컨테이너의 border 스타일 변경 및 HTML title 값 변경
  src/shopping/shopping.css
  src/shopping/shopping.html
Labels: feature, design

#51 refactor: 배경 색상 통일화
  src/befit-ai/befit-ai.css
Labels: design, frontend

#54 [문서화] 최종 발표 준비, 회의록 정리
  docs/meetings/2025-06-30-meeting.md
  docs/meetings/2025-07-01-meeting.md
  docs/meetings/2025-07-02-meeting.md
  index.html
  src/befit-ai/befit-ai.html
  src/playlist/playlist.html
  src/shopping/shopping.html
Labels: docs, discussion

#59 [기능] 개인정보 및 이용 모달 추가, [수정] 건강챗봇 프롬프트와 첫 메세지 수정
  assets/css/main.css
  assets/js/main.js
  index.html
  src/infermedica/infermedica.js
Labels: feature
